In [26]:
df[df["sms_sent"] < 0][
    ["customer_id", "calls_made", "sms_sent", "data_used", "churn"]
].head(10)

     customer_id  calls_made  sms_sent  data_used  churn
19            20          95        -1       9993      0
33            34          89        -2       3927      0
83            84         102        -1       7785      0
90            91          36        -3       2695      0
110          111          38        -4       3529      0
149          150          41        -1       5820      0
165          166          95        -2       2378      0
170          171          28        -1       4942      1
190          191          -3        -1       3838      1
252          253           5        -1       1811      0

In [25]:
df[df["calls_made"] < 0][
    ["customer_id", "calls_made", "sms_sent", "data_used", "churn"]
].head(10)

     customer_id  calls_made  sms_sent  data_used  churn
68            69          -1        13       8728      0
109          110          -3        24       3695      0
154          155          -5        42       9856      0
180          181         -10         9       8344      0
190          191          -3        -1       3838      1
212          213          -9        21       9798      1
216          217          -1        12       5243      0
243          244          -4        20       5952      0
249          250          -4        22       8154      0
282          283          -1        -4       1595      0

In [27]:


df[df["data_used"] < 0][
    ["customer_id", "calls_made", "sms_sent", "data_used", "churn"]
].head(10)

     customer_id  calls_made  sms_sent  data_used  churn
0              1          44        45       -361      0
38            39          92        15       -790      0
69            70          36         6       -492      0
72            73          33        44        -73      0
87            88          78         4       -149      1
107          108          13        26       -683      0
119          120          93         3       -478      1
133          134          10        26       -173      0
153          154          85        19       -482      0
182          183          47        12       -297      1

In [24]:
negative_counts = (df[numeric_columns] < 0).sum()

negative_counts

age                    0
num_dependents         0
estimated_salary       0
calls_made          6713
sms_sent            7375
data_used           6050
dtype: int64

## Data Quality Investigation

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv("../data/raw/telecom_churn.csv")

In [7]:
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [8]:
df.shape

(243553, 14)

In [9]:
df.head()

,customer_id,telecom_partner,gender,age,state,city,pincode,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,1,Reliance Jio,F,25,Karnataka,Kolkata,755597,2020-01-01,4,124962,44,45,-361,0
1,2,Reliance Jio,F,55,Mizoram,Mumbai,125926,2020-01-01,2,130556,62,39,5973,0
2,3,Vodafone,F,57,Arunachal Pradesh,Delhi,423976,2020-01-01,0,148828,49,24,193,1
3,4,BSNL,M,46,Tamil Nadu,Kolkata,522841,2020-01-01,1,38722,80,25,9377,1
4,5,BSNL,F,26,Tripura,Delhi,740247,2020-01-01,2,55098,78,15,1393,0

In [10]:
df.columns

Index(['customer_id', 'telecom_partner', 'gender', 'age', 'state', 'city',
       'pincode', 'date_of_registration', 'num_dependents', 'estimated_salary',
       'calls_made', 'sms_sent', 'data_used', 'churn'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243553 entries, 0 to 243552
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   customer_id           243553 non-null  int64
 1   telecom_partner       243553 non-null  object
 2   gender                243553 non-null  object
 3   age                   243553 non-null  int64
 4   state                 243553 non-null  object
 5   city                  243553 non-null  object
 6   pincode               243553 non-null  int64
 7   date_of_registration  243553 non-null  object
 8   num_dependents        243553 non-null  int64
 9   estimated_salary      243553 non-null  int64
 10  calls_made            243553 non-null  int64
 11  sms_sent              243553 non-null  int64
 12  data_used             243553 non-null  int64
 13  churn                 243553 non-null  int64
dtypes: int64(9), object(5)
memory usage: 26.0+ MB

In [12]:
df.isnull().sum()

customer_id             0
telecom_partner         0
gender                  0
age                     0
state                   0
city                    0
pincode                 0
date_of_registration    0
num_dependents          0
estimated_salary        0
calls_made              0
sms_sent                0
data_used               0
churn                   0
dtype: int64

In [13]:
df.duplicated().sum()

0

In [14]:
df["churn"].value_counts()

churn
0    194726
1     48827
Name: count, dtype: int64

In [15]:
df["churn"].value_counts(normalize=True) * 100

churn
0    79.952208
1    20.047792
Name: proportion, dtype: float64

In [16]:
df["telecom_partner"].value_counts()

telecom_partner
Reliance Jio    61123
Airtel          60905
Vodafone        60802
BSNL            60723
Name: count, dtype: int64

In [17]:
df["gender"].value_counts()

gender
M    145977
F     97576
Name: count, dtype: int64

In [18]:
df["state"].nunique()

28

In [19]:
df["city"].nunique()

6

In [20]:
df["customer_id"].nunique()

243553

In [21]:
df["customer_id"].duplicated().sum()

0

In [22]:
df[[
    "age",
    "num_dependents",
    "estimated_salary",
    "calls_made",
    "sms_sent",
    "data_used"
]].describe()

,age,num_dependents,estimated_salary,calls_made,sms_sent,data_used
count,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000,243553.000000
mean,46.077609,1.997500,85021.137839,49.010548,23.945404,4993.186025
std,16.444029,1.414941,37508.963233,29.453556,14.733575,2942.019547
min,18.000000,0.000000,20000.000000,-10.000000,-5.000000,-987.000000
25%,32.000000,1.000000,52585.000000,24.000000,11.000000,2490.000000
50%,46.000000,2.000000,84990.000000,49.000000,24.000000,4987.000000
75%,60.000000,3.000000,117488.000000,74.000000,36.000000,7493.000000
max,74.000000,4.000000,149999.000000,108.000000,53.000000,10991.000000

In [23]:
numeric_columns = [
    "age",
    "num_dependents",
    "estimated_salary",
    "calls_made",
    "sms_sent",
    "data_used"
]

(df[numeric_columns] < 0).sum()

age                    0
num_dependents         0
estimated_salary       0
calls_made          6713
sms_sent            7375
data_used           6050
dtype: int64

## Invalid Usage Values

In [28]:
usage_columns = ["calls_made", "sms_sent", "data_used"]

for col in usage_columns:
    print(f"\n{col}")
    print("Negative:", (df[col] < 0).sum())
    print("Zero:", (df[col] == 0).sum())
    print("Positive:", (df[col] > 0).sum())

calls_made
Negative: 6713
Zero: 1345
Positive: 235495

sms_sent
Negative: 7375
Zero: 2877
Positive: 233301

data_used
Negative: 6050
Zero: 14
Positive: 237489

In [29]:
for col in usage_columns:
    negative_pct = (df[col] < 0).mean() * 100
    print(f"{col}: {negative_pct:.2f}% negative")

calls_made: 2.76% negative
sms_sent: 3.03% negative
data_used: 2.48% negative

In [30]:
for col in usage_columns:
    print(f"\n{col}")
    print(
        df.groupby(df[col] < 0)["churn"]
        .agg(["count", "mean"])
    )

calls_made
             count     mean
calls_made
False       236840  0.20041
True          6713  0.20289

sms_sent
           count      mean
sms_sent
False     236178  0.200235
True        7375  0.208271

data_used
            count      mean
data_used
False      237503  0.200305
True         6050  0.207273

In [31]:
invalid_usage = (
    (df["calls_made"] < 0) |
    (df["sms_sent"] < 0) |
    (df["data_used"] < 0)
)

print("Customers with at least one invalid usage value:", invalid_usage.sum())
print("Percentage:", invalid_usage.mean() * 100)

Customers with at least one invalid usage value: 19587
Percentage: 8.042192048547955

In [32]:
df.loc[invalid_usage, usage_columns].head(20)

     calls_made  sms_sent  data_used
0            44        45       -361
19           95        -1       9993
33           89        -2       3927
38           92        15       -790
68           -1        13       8728
69           36         6       -492
72           33        44        -73
83          102        -1       7785
87           78         4       -149
90           36        -3       2695
107          13        26       -683
109          -3        24       3695
110          38        -4       3529
119          93         3       -478
133          10        26       -173
149          41        -1       5820
153          85        19       -482
154          -5        42       9856
165          95        -2       2378
170          28        -1       4942

In [33]:
df_clean = df.copy()

In [34]:
usage_columns = ["calls_made", "sms_sent", "data_used"]

for col in usage_columns:
    df_clean.loc[df_clean[col] < 0, col] = pd.NA

In [35]:
df_clean[usage_columns].isnull().sum()

calls_made    6713
sms_sent      7375
data_used     6050
dtype: int64

In [36]:
df_clean[usage_columns].describe()

          calls_made       sms_sent      data_used
count  236840.000000  236178.000000  237503.000000
mean       50.512384      24.765681    5128.756125
std        28.462247      14.198159    2852.135577
min         0.000000       0.000000       0.000000
25%        26.000000      13.000000    2675.000000
50%        50.000000      25.000000    5112.000000
75%        75.000000      37.000000    7557.000000
max       108.000000      53.000000   10991.000000

In [37]:
(df_clean[usage_columns] < 0).sum()

calls_made    0
sms_sent      0
data_used     0
dtype: int64

In [38]:
df_clean.shape

(243553, 14)

In [39]:
df_clean.to_csv(
    "../data/cleaned/telecom_churn_cleaned.csv",
    index=False
)

In [40]:
print("Churn rate for customers with invalid usage:")
print(df.loc[invalid_usage, "churn"].mean() * 100)

print("\nChurn rate for customers with valid usage:")
print(df.loc[~invalid_usage, "churn"].mean() * 100)

Churn rate for customers with invalid usage:
20.579976515035483

Churn rate for customers with valid usage:
20.001250189760945

In [41]:
df_clean = df.copy()

In [42]:
usage_columns = ["calls_made", "sms_sent", "data_used"]

for col in usage_columns:
    df_clean.loc[df_clean[col] < 0, col] = pd.NA

In [43]:
df_clean[usage_columns].isnull().sum()

calls_made    6713
sms_sent      7375
data_used     6050
dtype: int64

In [44]:
(df_clean[usage_columns] < 0).sum()

calls_made    0
sms_sent      0
data_used     0
dtype: int64

In [45]:
df_clean.shape

(243553, 14)

In [46]:
df_clean["date_of_registration"].head()

0    2020-01-01
1    2020-01-01
2    2020-01-01
3    2020-01-01
4    2020-01-01
Name: date_of_registration, dtype: object

In [47]:
df_clean["date_of_registration"].dtype

dtype('O')

In [48]:
df_clean["date_of_registration"] = pd.to_datetime(
    df_clean["date_of_registration"],
    errors="coerce"
)

In [49]:
df_clean["date_of_registration"].dtype

dtype('<M8[ns]')

In [50]:
df_clean["date_of_registration"].isnull().sum()

0

In [51]:
print("Earliest registration:", df_clean["date_of_registration"].min())
print("Latest registration:", df_clean["date_of_registration"].max())

Earliest registration: 2020-01-01 00:00:00
Latest registration: 2023-05-04 00:00:00

## Numerical Data Validation

In [52]:
df_clean["age"].describe()

count    243553.000000
mean         46.077609
std          16.444029
min          18.000000
25%          32.000000
50%          46.000000
75%          60.000000
max          74.000000
Name: age, dtype: float64

In [53]:
print("Minimum age:", df_clean["age"].min())
print("Maximum age:", df_clean["age"].max())

Minimum age: 18
Maximum age: 74

In [54]:
df_clean["num_dependents"].describe()

count    243553.000000
mean          1.997500
std           1.414941
min           0.000000
25%           1.000000
50%           2.000000
75%           3.000000
max           4.000000
Name: num_dependents, dtype: float64

In [55]:
print("Minimum dependents:", df_clean["num_dependents"].min())
print("Maximum dependents:", df_clean["num_dependents"].max())

Minimum dependents: 0
Maximum dependents: 4

In [56]:
df_clean["estimated_salary"].describe()

count    243553.000000
mean      85021.137839
std       37508.963233
min       20000.000000
25%       52585.000000
50%       84990.000000
75%      117488.000000
max      149999.000000
Name: estimated_salary, dtype: float64

In [57]:
print("Minimum salary:", df_clean["estimated_salary"].min())
print("Maximum salary:", df_clean["estimated_salary"].max())

Minimum salary: 20000
Maximum salary: 149999

In [58]:
df_clean["date_of_registration"].isnull().sum()

0

In [59]:
print("Earliest registration:", df_clean["date_of_registration"].min())
print("Latest registration:", df_clean["date_of_registration"].max())

Earliest registration: 2020-01-01 00:00:00
Latest registration: 2023-05-04 00:00:00

In [60]:
df_clean["num_dependents"].describe()

count    243553.000000
mean          1.997500
std           1.414941
min           0.000000
25%           1.000000
50%           2.000000
75%           3.000000
max           4.000000
Name: num_dependents, dtype: float64

In [61]:
print("Minimum dependents:", df_clean["num_dependents"].min())
print("Maximum dependents:", df_clean["num_dependents"].max())

Minimum dependents: 0
Maximum dependents: 4

In [62]:
df_clean["estimated_salary"].describe()

count    243553.000000
mean      85021.137839
std       37508.963233
min       20000.000000
25%       52585.000000
50%       84990.000000
75%      117488.000000
max      149999.000000
Name: estimated_salary, dtype: float64

In [63]:
print("Minimum salary:", df_clean["estimated_salary"].min())
print("Maximum salary:", df_clean["estimated_salary"].max())

Minimum salary: 20000
Maximum salary: 149999

In [64]:
print("Telecom partners:")
print(df_clean["telecom_partner"].unique())

print("\nGender:")
print(df_clean["gender"].unique())

print("\nStates:")
print(df_clean["state"].unique())

Telecom partners:
['Reliance Jio' 'Vodafone' 'BSNL' 'Airtel']

Gender:
['F' 'M']

States:
['Karnataka' 'Mizoram' 'Arunachal Pradesh' 'Tamil Nadu' 'Tripura'
 'Uttarakhand' 'Himachal Pradesh' 'Rajasthan' 'Odisha' 'Uttar Pradesh'
 'Chhattisgarh' 'Madhya Pradesh' 'Manipur' 'Goa' 'West Bengal' 'Gujarat'
 'Telangana' 'Maharashtra' 'Haryana' 'Andhra Pradesh' 'Sikkim' 'Assam'
 'Jharkhand' 'Kerala' 'Punjab' 'Nagaland' 'Bihar' 'Meghalaya']

In [65]:
print("Churn values:")
print(df_clean["churn"].unique())

Churn values:
[0 1]

In [66]:
df_clean.isnull().sum()

customer_id                0
telecom_partner            0
gender                     0
age                        0
state                      0
city                       0
pincode                    0
date_of_registration       0
num_dependents             0
estimated_salary           0
calls_made              6713
sms_sent                7375
data_used               6050
churn                      0
dtype: int64

In [67]:
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])

Rows: 243553
Columns: 14

In [68]:
df_clean.to_csv(
    "../data/cleaned/telecom_churn_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!